# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4c7442e3b322959b154f89be0c863171fe6743ba4f54a40b79d41ebfd17db892f8de33235708a4ba58dd35d98447535d3a2f3523a11a23b1af44c98b1295adb

test:
  secret_key_base: f2b7838bbfe8d1f3a42c3dbabdce309f8217dfd137b8a0ceecad3e333a8b46b3d0a78d0f856cbac5678c3080bd1b048e23fb4ea8f0685e160979253bc82058cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
